site_name: Dorm Chores Schedule Documntation
site_description: Documentation for the Dorm Chores Schedule project
site_author: Group 7 (Team C)

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Components: components.md
